### PR TITLE
Game Crash on "No Path Found" Error #5 Fixed

### LINKED ISSUE #5: Game hangs when Astar cant find a path to food.

### PR DESCRIPTION
**Pull request by aym-n**
Resolved game crashes when the snake couldn't find a path to the food by checking for a valid path. fixes #5

### CODE REVIEW

File: src/astar.rs
Comment (cyberphantom52) [inline src/astar.rs:1]: The better way to do it would be to return an `Option` and use unwrap to check if path was found.

File: src/astar.rs [hunk 1]
```diff
@@ -91,10 +94,14 @@ pub fn find_path(map: &mut Map, start: Vector, destination: Vector) -> Vec<Vecto
...
-    while current.pos.x != start.x || current.pos.y != start.y {
+    while (current.pos.x != start.x || current.pos.y != start.y) && path_found {
         path.push(current.pos);
         current = map[current.parent_pos.y as usize][current.parent_pos.x as usize];
     }
 
+    if !path_found {
+        path.clear();
+    }
+    println!("Path length: {}", path.len());
```
Comment (cyberphantom52) [inline src/astar.rs]: Don't need to print path length

File: src/astar.rs
Comment (cyberphantom52) [reply src/astar.rs:1]: You can also typedef `Path` to be a `Vec<Vector>`. Not sure if it'll conflict with rust`s built-in `Path` type.

File: src/game.rs [hunk 2]
```diff
@@ -130,7 +135,7 @@ impl Game {
             self.event_handler();
             self.update();
             self.draw();
-            std::thread::sleep(std::time::Duration::from_millis(10));
+            std::thread::sleep(std::time::Duration::from_millis(1));
```
Comment (cyberphantom52) [inline src/game.rs]: Seems unnecessary? Why is this part of this MR

File: src/utils.rs [hunk 3]
```diff
@@ -16,7 +16,7 @@ pub (crate) use wrap_x;
 pub (crate) use wrap_y;
 
 
-#[derive(Eq, Hash, Copy, Clone)]
+#[derive(Eq, Hash, Copy, Clone, Debug)]
```
Comment (cyberphantom52) [inline src/utils.rs]: All changes made to this file are unrelated to this MR, please revert.

**Comment by cyberphantom52** [comment]
LGTM!, from next time please create a separate branch when you want to contribute.
